<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" tests="19" skipped="0" failures="0" errors="0" timestamp="2020-01-15T02:08:09" hostname="localhost" time="6.55">
  <properties/>
  <testcase name="testMetadataFailurePropagated" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="2.25"/>
  <testcase name="testTrySend" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.042"/>
  <testcase name="multiSend" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.905"/>
  <testcase name="testInvalidTopicExceptionPropagatedFromMetadata" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.192"/>
  <testcase name="sendWithinBlackoutPeriodAfterAuthenticationFailure" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.001"/>
  <testcase name="wakeup" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.001"/>
  <testcase name="testTimeoutUnsentRequest" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.001"/>
  <testcase name="testDisconnectWithInFlightRequests" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.001"/>
  <testcase name="blockWhenPollConditionNotSatisfied" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="3.032"/>
  <testcase name="send" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.001"/>
  <testcase name="testAuthenticationExceptionPropagatedFromMetadata" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.001"/>
  <testcase name="sendExpiry" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.002"/>
  <testcase name="blockOnlyForRetryBackoffIfNoInflightRequests" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.003"/>
  <testcase name="testAwaitForMetadataUpdateWithTimeout" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.001"/>
  <testcase name="testDisconnectWakesUpPoll" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.001"/>
  <testcase name="testTopicAuthorizationExceptionPropagatedFromMetadata" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.001"/>
  <testcase name="testFutureCompletionOutsidePoll" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.108"/>
  <testcase name="doNotBlockIfPollConditionIsSatisfied" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.003"/>
  <testcase name="testDisconnectWithUnsentRequests" classname="org.apache.kafka.clients.consumer.internals.ConsumerNetworkClientTest" time="0.0"/>
  <system-out><![CDATA[[2020-01-15 10:08:13,334] ERROR Metadata response reported invalid topics [topic] (org.apache.kafka.clients.Metadata:274)
[2020-01-15 10:08:16,416] ERROR Topic authorization failed for topics [topic] (org.apache.kafka.clients.Metadata:281)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
